use anyhow::Result;

use crate::templates::TemplateRegistry;

use super::config::HarnessConfig;

pub(super) fn codex_agents_md(registry: &TemplateRegistry) -> Result<String> {
    let config = HarnessConfig::from_registry(registry)?;
    let skills = registry
        .skills()
        .iter()
        .map(|skill| format!("- `{}`", skill.name))
        .collect::<Vec<_>>()
        .join("\n");
    let default_active_skills = if config.default_active_skills.is_empty() {
        "- none".to_string()
    } else {
        config
            .default_active_skills
            .iter()
            .map(|skill| format!("- `{skill}`"))
            .collect::<Vec<_>>()
            .join("\n")
    };
    let tools = registry
        .tools()
        .iter()
        .map(|tool| {
            format!(
                "- `{}`: read `{}` only when needed",
                tool.name, tool.relative_path
            )
        })
        .collect::<Vec<_>>()
        .join("\n");
    let agents = registry
        .agents()
        .iter()
        .map(|agent| format!("- `{}`", agent.name))
        .collect::<Vec<_>>()
        .join("\n");

    Ok(format!(
        r#"# Megara Codex Harness

This file is generated by Megara. Edit the Megara SSOT, then run `megara sync`.

## Locale

- Locale: `{}`.
- Write user-facing prose in the configured locale unless the user explicitly requests another language.
- Keep code identifiers, file paths, commands, config keys, package names, API names, and quoted source text unchanged.
- For technical concepts, prefer natural terms in the configured locale when they exist. If an English-only technical term must remain, add a short explanation in the configured locale on first use.
- Do not mix languages in explanatory prose. Structured block keys stay parseable, while free-text values follow the configured locale unless they are technical literals.

## Skills

{}

## Default Active Skills

{}

## On-Demand Tools

{}

- On-demand tools are not default active skills.
- Use them only when the user's request or a failed lightweight route needs that tool.
- Project scope stores tool files under `.agents/tools`; global scope stores them under `~/.megara/tools`.
- Prefer `.agents/bin/<tool-name>` in project scope and `~/.megara/bin/<tool-name>` in global scope when a wrapper exists.

## Agents

{}

## Planning Adapter

- Planning state is owned by the deterministic Planning Core under `.megara/planning`.
- Use the returned typed work item and current state; do not infer approval or mutate planning state outside the supported entrypoints.
- Approval and purge operations require an explicit user entrypoint.

## Codex Runtime Adapter

- Use `request_user_input` for a material clarification outside an active Planning Core flow only when `default_mode_request_user_input` is enabled by this projection and the current runtime exposes the tool. Ask one to three short decision questions, give two or three mutually exclusive choices, put the recommended choice first, and preserve a free-text fallback.
- If the feature is unavailable, use the existing concise Markdown clarification flow instead of calling `request_user_input`.
- During an active Planning Core flow, use its state-compatible question and answer protocol so the store can persist and recover the decision.

## Rules

- Clarify ambiguity before implementation.
- Keep implementation scoped to the accepted plan.
- Verify behavior before the final response.
"#,
        config.locale, skills, default_active_skills, tools, agents
    ))
}
