use std::{fs, path::Path};

use anyhow::{bail, Context, Result};
use toml_edit::DocumentMut;

use crate::installer::{ManagedTomlEdit, MANAGED_MARKER};

use super::mcp_config::{
    configure_default_mode_request_user_input, remove_marker_line,
    DEFAULT_MODE_REQUEST_USER_INPUT_MARKER,
};

const BASE_CONFIG: &str = "# MEGARA:MANAGED generated by Megara. Edit SSOT and run `megara sync`.\n# Megara Codex projection.\n# Codex discovers skills and agents from this directory.\n";

pub(super) fn plan(
    root: &Path,
    runtime_supports_default_mode_request_user_input: bool,
    force: bool,
) -> Result<Option<ManagedTomlEdit>> {
    let path = root.join("config.toml");
    let (source, existing, permissions) = match read_existing(&path)? {
        Some((source, existing, permissions)) => (Some(source), Some(existing), Some(permissions)),
        None => (None, None, None),
    };
    let base = existing.as_deref().unwrap_or(BASE_CONFIG);
    let (without_marker, feature_marker_present) =
        remove_marker_line(base, DEFAULT_MODE_REQUEST_USER_INPUT_MARKER);
    let mut document: DocumentMut = without_marker
        .parse()
        .context("failed to parse Codex config TOML")?;
    let (_, feature_is_managed) = configure_default_mode_request_user_input(
        &mut document,
        runtime_supports_default_mode_request_user_input,
        feature_marker_present,
    )?;
    let existing_is_managed = existing
        .as_deref()
        .is_some_and(|existing| existing.contains(MANAGED_MARKER));
    if existing.is_some() && !existing_is_managed && !feature_marker_present && !feature_is_managed
    {
        return Ok(None);
    }
    let mut desired = document.to_string();
    if !desired.ends_with('\n') {
        desired.push('\n');
    }
    if feature_is_managed {
        desired.push_str(DEFAULT_MODE_REQUEST_USER_INPUT_MARKER);
        desired.push('\n');
    }

    let changed = source
        .as_deref()
        .is_none_or(|source| source != desired.as_bytes());
    if changed && existing.is_some() && !existing_is_managed && !feature_marker_present && !force {
        bail!(
            "refusing to modify unmanaged Codex config {}; rerun with --force",
            path.display()
        );
    }

    Ok(Some(ManagedTomlEdit {
        path,
        created: source.is_none(),
        changed,
        backup_path: None,
        desired,
        backup: None,
        expected_source: source,
        permissions,
    }))
}

pub(super) fn plan_remove(root: &Path) -> Result<Option<ManagedTomlEdit>> {
    let path = root.join("config.toml");
    let Some((source, existing, permissions)) = read_existing(&path)? else {
        return Ok(None);
    };
    let (without_marker, feature_marker_present) =
        remove_marker_line(&existing, DEFAULT_MODE_REQUEST_USER_INPUT_MARKER);
    if !feature_marker_present {
        return Ok(None);
    }
    let mut document: DocumentMut = without_marker
        .parse()
        .context("failed to parse Codex config TOML")?;
    configure_default_mode_request_user_input(&mut document, false, true)?;
    let desired = document.to_string();
    Ok(Some(ManagedTomlEdit {
        path,
        created: false,
        changed: desired.as_bytes() != source.as_slice(),
        backup_path: None,
        desired,
        backup: None,
        expected_source: Some(source),
        permissions: Some(permissions),
    }))
}

fn read_existing(path: &Path) -> Result<Option<(Vec<u8>, String, fs::Permissions)>> {
    let source = match fs::read(path) {
        Ok(source) => source,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(None),
        Err(error) => {
            return Err(error)
                .with_context(|| format!("failed to read Codex config {}", path.display()))
        }
    };
    let content = String::from_utf8(source.clone())
        .with_context(|| format!("Codex config is not valid UTF-8: {}", path.display()))?;
    let permissions = fs::metadata(path)
        .with_context(|| format!("failed to stat Codex config {}", path.display()))?
        .permissions();
    Ok(Some((source, content, permissions)))
}
