use super::*;

#[cfg(unix)]
#[test]
fn update_refreshes_project_harness_and_removes_obsolete_projection() {
    use std::os::unix::fs::PermissionsExt;

    let dir = tempdir().unwrap();
    let home = tempdir().unwrap();
    let codex_home = tempdir().unwrap();
    let fake_bin = tempdir().unwrap();
    let fallback_runtime = tempdir().unwrap();
    let obsolete_skill = dir.path().join(
        super::planning::migration::inventory::managed_projection_paths()
            .iter()
            .find(|path| path.contains("/skills/"))
            .unwrap(),
    );

    write_codex_runtime(fallback_runtime.path(), false);
    let initial_path = format!(
        "{}:{}",
        fallback_runtime.path().display(),
        std::env::var("PATH").unwrap_or_default()
    );
    let install = megara_with_codex_home(codex_home.path())
        .args([
            "install",
            "--scope",
            "project",
            "--target",
            "codex",
            "--trust-project",
            "--no-interactive",
        ])
        .env("PATH", initial_path)
        .current_dir(dir.path())
        .output()
        .unwrap();
    assert!(
        install.status.success(),
        "stderr={}",
        String::from_utf8_lossy(&install.stderr)
    );
    let config = dir.path().join(".codex/config.toml");
    assert!(!fs::read_to_string(&config)
        .unwrap()
        .contains("default_mode_request_user_input"));
    fs::create_dir_all(obsolete_skill.parent().unwrap()).unwrap();
    fs::write(
        &obsolete_skill,
        "<!-- MEGARA:MANAGED generated by Megara. -->\nlegacy",
    )
    .unwrap();
    let legacy_state = dir.path().join(".agents/state/legacy-plan.json");
    fs::create_dir_all(legacy_state.parent().unwrap()).unwrap();
    fs::write(&legacy_state, r#"{"session_id":"legacy-plan"}"#).unwrap();
    assert!(obsolete_skill.exists());
    assert!(legacy_state.exists());

    let curl = fake_bin.path().join("curl");
    fs::write(
        &curl,
        format!(
            "#!/bin/sh\nprintf '%s\\n' '{{\"tag_name\":\"v{}\"}}'\n",
            env!("CARGO_PKG_VERSION")
        ),
    )
    .unwrap();
    let mut permissions = fs::metadata(&curl).unwrap().permissions();
    permissions.set_mode(0o755);
    fs::set_permissions(&curl, permissions).unwrap();
    write_codex_runtime(fake_bin.path(), true);

    let path = format!(
        "{}:{}",
        fake_bin.path().display(),
        std::env::var("PATH").unwrap_or_default()
    );
    let output = megara_with_codex_home(codex_home.path())
        .arg("update")
        .arg("--scope")
        .arg("project")
        .arg("--target")
        .arg("codex")
        .env("HOME", home.path())
        .env("PATH", path)
        .current_dir(dir.path())
        .output()
        .unwrap();

    assert!(
        output.status.success(),
        "stderr={}",
        String::from_utf8_lossy(&output.stderr)
    );
    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(stdout.contains("Megara / Update"));
    assert!(stdout.contains("Megara binary is current"));
    assert!(stdout.contains("Refreshing harness: scope=project, target=codex"));
    assert!(stdout.contains("Megara update complete."));
    assert!(!obsolete_skill.exists());
    assert!(!dir.path().join(".agents/state").exists());
    assert!(dir.path().join(".megara/state/legacy-plan.json").exists());
    assert!(dir.path().join(".agents/.gitignore").exists());
    assert!(dir.path().join(".megara/.gitignore").exists());
    assert!(dir
        .path()
        .join(".agents/tools/insane-search/TOOL.md")
        .exists());
    assert!(dir
        .path()
        .join(".agents/skills/insane-search/SKILL.md")
        .exists());
    assert!(dir.path().join(".agents/skills/caveman/SKILL.md").exists());
    assert!(dir
        .path()
        .join(".agents/skills/agent-models/SKILL.md")
        .exists());
    assert!(dir.path().join(".agents/bin/insane-search").exists());
    let updated_config = fs::read_to_string(config).unwrap();
    assert!(updated_config.contains("default_mode_request_user_input = true"));
    assert!(updated_config.contains("MEGARA:DEFAULT-MODE-REQUEST-USER-INPUT"));
    let wrapper = fs::read_to_string(dir.path().join(".agents/bin/insane-search")).unwrap();
    assert!(wrapper.contains(r#"runtime_root="$root_dir/../.megara""#));
    assert!(wrapper.contains("state/tools/insane-search"));
    assert!(wrapper.contains("pip install -r"));
}

#[cfg(unix)]
#[test]
fn update_refreshes_pi_process_helper_from_ssot() {
    use std::os::unix::fs::PermissionsExt;

    let dir = tempdir().unwrap();
    let home = tempdir().unwrap();
    let fake_bin = tempdir().unwrap();
    let install = megara()
        .args([
            "install",
            "--scope",
            "project",
            "--target",
            "pi",
            "--no-interactive",
        ])
        .current_dir(dir.path())
        .output()
        .unwrap();
    assert!(install.status.success());

    let projected_helper = dir.path().join(".pi/megara_process.ts");
    let original_helper = fs::read_to_string(&projected_helper).unwrap();
    fs::remove_file(&projected_helper).unwrap();

    let curl = fake_bin.path().join("curl");
    fs::write(
        &curl,
        format!(
            "#!/bin/sh\nprintf '%s\\n' '{{\"tag_name\":\"v{}\"}}'\n",
            env!("CARGO_PKG_VERSION")
        ),
    )
    .unwrap();
    fs::set_permissions(&curl, fs::Permissions::from_mode(0o755)).unwrap();
    let path = format!(
        "{}:{}",
        fake_bin.path().display(),
        std::env::var("PATH").unwrap_or_default()
    );
    let update = megara()
        .args([
            "update",
            "--scope",
            "project",
            "--target",
            "pi",
            "--no-interactive",
        ])
        .env("HOME", home.path())
        .env("PATH", path)
        .current_dir(dir.path())
        .output()
        .unwrap();
    assert!(
        update.status.success(),
        "stderr={}",
        String::from_utf8_lossy(&update.stderr)
    );
    assert_eq!(
        fs::read_to_string(projected_helper).unwrap(),
        original_helper
    );
    assert!(String::from_utf8_lossy(&update.stdout)
        .contains("Refreshing harness: scope=project, target=pi"));
}
